spark:
  cluster:
    master: "local"
  dynamicAllocation:
    enabled: false
    min:
      executors: "2"
  kubernetes:
    namespace: "gr-vtl"
    container:
      image: "hadrienkohl/spark:3.0.1"
    executor:
      request:
        cores: "100m"
    driver:
      pod:
        name: "test"
  hadoop:
    fs:
      s3a:
        access:
          key: ""
        secret:
          key: ""
        connection:
          ssl:
            enabled: true
        session:
          token: ""
        endpoint: ""
        aws:
          credentials:
            provider: "org.apache.hadoop.fs.s3a.TemporaryAWSCredentialsProvider"
auth:
  mode: "NONE"
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ""
jwt:
  username-claim: "preferred_username"
