spark:
  cluster:
    master: "local"
  hadoop:
    fs:
      s3a:
        access:
          key: ""
        secret:
          key: ""
        connection:
          ssl:
            enabled: true
        session:
          token: ""
        endpoint: ""
        aws:
          credentials:
            provider: "org.apache.hadoop.fs.s3a.TemporaryAWSCredentialsProvider"
auth-type: "NONE"
jwt:
  username-claim: "preferred_username"
