auth:
  mode: "NONE"
spark:
  cluster:
    master:
      local: "local"
      static: "local"
      kubernetes: "local"
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ""
jwt:
  username-claim: "preferred_username"
