apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trevas-lab-role-binding
subjects:
  - kind: ServiceAccount
    name: trevas-lab-sa
    namespace: my_namespace
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
