apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  namespace: my_namespace
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "services"
      - "configmaps"
    verbs:
      - "list"
      - "create"
      - "delete"
      - "watch"
      - "update"
      - "get"
      - "patch"
